name: 12H Stream

on:
  workflow_dispatch:
    inputs:
      run_count:
        description: 'Run count'
        default: '1'
        required: false

jobs:
  live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install System Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb ffmpeg pulseaudio
          pulseaudio -D --exit-idle-time=-1
          pacmd load-module module-virtual-sink sink_name=vss
          pacmd set-default-sink vss
          Xvfb :99 -screen 0 1920x1080x24 &

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Script
        env:
          YT_STREAM_KEY: ${{ secrets.YT_STREAM_KEY }}
          DISPLAY: :99
        run: |
          pip install selenium webdriver-manager
          python streamyard_bot.py

      - name: Restart Round
        if: always()
        run: |
          CURRENT_RUN=${{ github.event.inputs.run_count || '1' }}
          if [ "$CURRENT_RUN" -lt "2" ]; then
            curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/stream.yml/dispatches \
            -d '{"ref":"main", "inputs": {"run_count": "2"}}'
          fi
          
